# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upftp < Formula
  desc "Modern cross-platform file sharing server"
  homepage "https://github.com/zy84338719/upftp"
  version "2.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/zy84338719/upftp/releases/download/v2.2.0/upftp_Darwin_x86_64.tar.gz"
      sha256 "9c83451380104b6ff8a1d022963e8ec7d963078a6ef8dd7da01eec286bd5dc19"

      def install
        bin.install "upftp"
      end
    end
    on_arm do
      url "https://github.com/zy84338719/upftp/releases/download/v2.2.0/upftp_Darwin_arm64.tar.gz"
      sha256 "840cc0883faccbbae666dbb6b8e73e5fd116ec32ec251d0ac3bd21e1d56ee54e"

      def install
        bin.install "upftp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zy84338719/upftp/releases/download/v2.2.0/upftp_Linux_x86_64.tar.gz"
        sha256 "02587c7914f1de20224bdda43dcc96e8edac0727d0b2971d719f4ca0dda26fa5"

        def install
          bin.install "upftp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zy84338719/upftp/releases/download/v2.2.0/upftp_Linux_arm64.tar.gz"
        sha256 "53613238ee125a75d0f7e0d8c7d22b3829c0951fde7252ccd36ce90d2955a074"

        def install
          bin.install "upftp"
        end
      end
    end
  end

  service do
    run [opt_bin/"upftp", "-auto", "-d", var/"upftp"]
    keep_alive true
    log_path var/"log/upftp.log"
    error_log_path var/"log/upftp.error.log"
    working_dir var/"upftp"
  end

  test do
    system "#{bin}/upftp", "-h"
  end
end
