# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upftp < Formula
  desc "Modern cross-platform file sharing server"
  homepage "https://github.com/zy84338719/upftp"
  version "2.3.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/zy84338719/upftp/releases/download/v2.3.6/upftp_Darwin_x86_64.tar.gz"
      sha256 "7d23c56a4b6a8e89363999e8f39a910134f69ceb42125d81d73d50d451273be8"

      def install
        bin.install "upftp"
      end
    end
    on_arm do
      url "https://github.com/zy84338719/upftp/releases/download/v2.3.6/upftp_Darwin_arm64.tar.gz"
      sha256 "043fec97c6ecfcbc8b8c106b9dd94eee092cd8cbd8f86183a66a2a8b9ab8399d"

      def install
        bin.install "upftp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zy84338719/upftp/releases/download/v2.3.6/upftp_Linux_x86_64.tar.gz"
        sha256 "6e9fb9438d76fc5c92722c8207ec21841649d8b9fd7e14c7c5fa6ba91ae40ad1"

        def install
          bin.install "upftp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zy84338719/upftp/releases/download/v2.3.6/upftp_Linux_arm64.tar.gz"
        sha256 "e9dc3cb4880ac71315c6dabc5013ed2623f0f5ca7b46f8609b9e2621f18aa273"

        def install
          bin.install "upftp"
        end
      end
    end
  end

  service do
    run [opt_bin/"upftp", "-auto", "-d", var/"upftp"]
    keep_alive true
    log_path var/"log/upftp.log"
    error_log_path var/"log/upftp.error.log"
    working_dir var/"upftp"
  end

  test do
    system "#{bin}/upftp", "-h"
  end
end
