# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upftp < Formula
  desc "Modern cross-platform file sharing server with HTTP and FTP support"
  homepage "https://github.com/zy84338719/upftp"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zy84338719/upftp/releases/download/v0.1.7/upftp_Darwin_x86_64.tar.gz"
      sha256 "f0f2f40d33658713fcf8b63cb63fd3bbf5bf3cf8a398261d6b2aa310ba3f07b0"

      define_method(:install) do
        bin.install "upftp"

        # Create configuration directory
        (buildpath/"upftp.example.yaml").write_file
        etc.install "upftp.example.yaml" => "upftp/upftp.example.yaml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zy84338719/upftp/releases/download/v0.1.7/upftp_Darwin_arm64.tar.gz"
      sha256 "ccf03c093bcd340985d237afb566f1405ba26b0b0fa9386596ed58f78e80c2a3"

      define_method(:install) do
        bin.install "upftp"

        # Create configuration directory
        (buildpath/"upftp.example.yaml").write_file
        etc.install "upftp.example.yaml" => "upftp/upftp.example.yaml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zy84338719/upftp/releases/download/v0.1.7/upftp_Linux_x86_64.tar.gz"
      sha256 "7a25169bb72ef4bf6fc60a5c804503b04986a77cb4d7ced17529bf41f462a157"
      define_method(:install) do
        bin.install "upftp"

        # Create configuration directory
        (buildpath/"upftp.example.yaml").write_file
        etc.install "upftp.example.yaml" => "upftp/upftp.example.yaml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zy84338719/upftp/releases/download/v0.1.7/upftp_Linux_arm64.tar.gz"
      sha256 "7a0e0cc5225f0cfe04899808a598d06cbeb8cd1b1c6384359597dd0fd25fbc56"
      define_method(:install) do
        bin.install "upftp"

        # Create configuration directory
        (buildpath/"upftp.example.yaml").write_file
        etc.install "upftp.example.yaml" => "upftp/upftp.example.yaml"
      end
    end
  end

  service do
    run [opt_bin/"upftp", "-auto", "-d", var/"upftp"]
    keep_alive true
    log_path var/"log/upftp.log"
    error_log_path var/"log/upftp.error.log"
    working_dir var/"upftp"
  end

  test do
    system "#{bin}/upftp", "-h"
  end
end
